name: Rebalance portfolio

on:
  workflow_dispatch:
  schedule:
    - cron:  '22 15 * * 1-5'

env:
  GITHUB_PAT: ${{ secrets.GH_PAT }}
  ALPACA_PAPER_KEY: ${{ secrets.ALPACA_PAPER_KEY }}
  ALPACA_PAPER_SECRET: ${{ secrets.ALPACA_PAPER_SECRET }}
  ALPACA_LIVE_KEY: ${{ secrets.ALPACA_LIVE_KEY }}
  ALPACA_LIVE_SECRET: ${{ secrets.ALPACA_LIVE_SECRET }}
  
jobs:
  scheduled:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Run rebalancer
        run: |-
          Rscript rebalance.R
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
