name: Rebalance Paper Alpaca Portfolio

on:
  workflow_dispatch:
  schedule:
    - cron:  '22 18 * * 1-5'

env:
  GITHUB_PAT: ${{ secrets.GH_PAT }}
  ALPACA_PAPER_KEY: ${{ secrets.ALPACA_PAPER_KEY }}
  ALPACA_PAPER_SECRET: ${{ secrets.ALPACA_PAPER_SECRET }}
  ALPACA_LIVE_KEY: ${{ secrets.ALPACA_LIVE_KEY }}
  ALPACA_LIVE_SECRET: ${{ secrets.ALPACA_LIVE_SECRET }}

jobs:
  rebalance:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2


      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: Rscript install.R

      - name: Run rebalancer
        run: |-
          Rscript rebalance.R

      - name: Commit results
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push